apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - image: ghcr.io/pluhin/22busy-box:latest
      command:
      - "sleep"
      - "604800"
      imagePullPolicy: IfNotPresent
      name: ubuntu
  restartPolicy: Always