name: k3s check pods

on: 
  push:
  #schedule:
  #  - cron: "*/10 * * * *"
env:
  report: report.log

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to K3S host
        id: get_pods
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{ secrets.SSH_KEY }}" 
           ssh-keyscan -H ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts
           ssh ${{ secrets.BASTION_UN }}@${{ secrets.BASTION_IP}} ssh-keyscan ${{ secrets.K3SHOST_IP }} >> ~/.ssh/known_hosts
           ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.BASTION_UN }}@${{ secrets.BASTION_IP }}" ${{ secrets.K3SHOST_UN }}@${{ secrets.K3SHOST_IP }} "kubectl get pods -A" >> report  
      
      - name: slack Notification
        uses: rtCamp/action-slack-notify@v2 
        env:
          SLACK_CHANNEL: github_notifications
          SLACK_TITLE: 'CHECK PODS'
          SLACK_USERNAME: ntBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: upload pod's list
        uses: actions/upload-artifact@v2
        with:
          path: report
